### ISSUE TITLE
hii

### ISSUE THREAD

**Issue by KingGamerXd** [superischroma/GreenHam#6]
Spectaculation is great plugin but it kinda outdated can you work on it again or will you continue this again in future?? overwise it is a very good plugin there are many other plugin also but these all bugged i hope it will be continue again in future

**Comment by ajaxvp** [comment]
I don't work on that project any more. I haven't worked on it in 2 years. You can update it yourself or get someone else do it, but I am done with it.

**Comment by KingGamerXd** [comment]
oh i hope spectaculation will continune again by someone else.
 sry for disturb
